services:
  vrising:
    image: trueosiris/vrising
    entrypoint: ["/bin/bash", "-c", "sed -i 's/\\r//g' /start.sh && exec /bin/bash /start.sh"]
    environment:
      - TZ=Europe/Paris
      - SERVERNAME=vrising-TrueOsiris2026
      - WINEDEBUG=fixme-all
    volumes:
      - type: bind
        source: /your/host/vrising/server
        target: /mnt/vrising/server
        bind:
          create_host_path: true
      - type: bind
        source: /your/host/vrising/persistentdata
        target: /mnt/vrising/persistentdata
        bind:
          create_host_path: true
    ports:
      - '9876:9876/udp'
      - '9877:9877/udp'
    restart: unless-stopped
    network_mode: bridge
