---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vrisingpersistendata
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: my-storage-class
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vrisingserverdata
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: my-storage-class
  accessModes:
    - ReadWriteOnce